### ISSUE TITLE
Multiple DB support

### ISSUE THREAD

**Issue by ryanemerson** [gingersnap-project/cache-manager#28]
Currently the DatabaseHandler injects a vertx Pool instance, however the implementation is tied to the `quarkus.datasource.db-kind` property which can only be configured at build time.

In order to support multiple DBs in testing/release we have a few options:

# Define multiple datasource providers, selecting the appropriate one at runtime.

Pros:
- Simple
- Single maven module

Cons:
- Really doesn't scale as we add more DBs :slightly_frowning_face: 

# Per DB build

Pros:
- Leanest builds

Cons:
- More complex release/testing

# Hybrid. Per DB build for releases, but utilise multiple datasource providers in dev mode

Pros:
- Simpler dev
- Testsuite for all supported DBs can be ran from single maven module
- Release only contains DB specific dependencies

Cons:
- More complex release
- Local testing is not against single provider (we will test this as part of the release though).

**Comment by wburns** [comment]
The more I am thinking, I think we will want to have different quarkus test profiles for running tests. I fear otherwise we will have too many problems with leakage between tests. This would work better with the first two (not hybrid) as I think about it.

**Comment by wburns** [comment]
https://quarkus.io/guides/getting-started-testing#testing_different_profiles

**Comment by ryanemerson** [comment]
That makes sense to me, given that we're already using them. My main concern/query with that before was how we handle `quarkus.datasource.db-kind=` being a build time config property, but  I think `@QuarkusIntegrationTest` helps us here.

**Comment by wburns** [comment]
db-kind isn't an issue with the first mode. The second one would be and would require IntegrationTest for sure. I am not sure which we want to do yet though, heh.
